name: Test installer

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  installer:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: bash -n install.sh tests/test-install.sh
      - run: bash tests/test-install.sh
